### ISSUE TITLE
Screencast • Screencast

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/textile#16]
See also #3 

----------------------------------------------------------

См. также #3

**Comment by olgapavlova** [comment]
Первая версия есть (ссылочку бы?).
Копим правки. По итогам — или переписываем, или просто буквами сложим эти уточнения рядом с видео.

**Comment by ArinaBaygildina** [comment]
https://youtu.be/YcRoCtANwbE 
Готов и выложен на Ютуб
