### ISSUE TITLE
Create list of everyday problems our tool helps to sort out • Составить список проблем, которые инструмент помогает решить

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/Textile#17]
Нам бы нужно собрать и вести список проблем, которые решает инструмент.
Вот, например, очевидная проблема: с его помощью легко можно протестировать прототип на устойчивость к переменным текстам.
Ещё проблема: при его использовании копирайтеру не нужна лицензия на Figma, а это экономия.
И так далее.

**Comment by ArinaBaygildina** [comment]
https://docs.google.com/document/d/1WlSicpE7kyyELNmUbhAAgJuKuo7Roa0C4XmesNPGNn0/edit - список проблем

**Comment by olgapavlova** [comment]
В работе.
