### ISSUE TITLE
Multi page download from Figma to GS • Реализовать мультистраничную выгрузку из Figma

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/textile#26]
При этом оставить функциональность «Загружаем-выгружаем отдельную страницу, а остальные не трогаем».

**Comment by roman-nebel** [comment]
На стороне  плагина и сервера все готово. Дело за таблицами.

**Comment by olgapavlova** [comment]
Таблицы ОК. Тестируем. @ArinaBaygildina

**Comment by olgapavlova** [comment]
Всё работает, начинаем писать help.
