### ISSUE TITLE
Interactive step-by-step promo • Интерактивное пошаговое промо

### ISSUE THREAD

**Issue by olgapavlova** [eduhund/textile#3]
It would be fine to provide some media support for beta testers.

----------------------------------------------------------

Было бы славно обеспечить бета-тестерам какие-нибудь медиаматериалы.

- [ ] Screencast • Скринкаст
- [ ] Interactive step-by-step promo • Интерактивное пошаговое промо

**Comment by olgapavlova** [comment]
Интерактивное промо работает только в Google Chrome. Но там не работают dev-плагины Figma. Как только сможем релизить плагин в community #7, можно будет записать и промо Figma-части.

А пока можно записать промо только табличной части.

**Comment by olgapavlova** [comment]
Скринкаст — в отдельной задаче #16

**Comment by olgapavlova** [comment]
А ссылочку бы?

**Comment by ArinaBaygildina** [comment]
https://drive.google.com/drive/u/1/folders/1nm5v6nB8Gk0D9kdGPyIE1mNsINi2IWEq - папка с видео

**Comment by ArinaBaygildina** [comment]
Интерактивное промо готово https://app.arcade.software/share/sSKdaY4FhCCCGKlkjbxG
